baseurl = "https://gerblesh.github.io"
title = "Gareth Widlansky"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

pagination.pagerSize = 20

# [services]
# [services.disqus]
# disqusShortname = "Gareth"
[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true


[params]
author = "Gareth Widlansky"
info = "Game Developer, Student, and OSS Contributor"
description = "Gareth Widlansky's Personal Website"
keywords = "blog,developer,personal"
avatarurl = "face.jpeg"
#gravatar = "john.doe@example.com"

faviconSVG = "avatar.webp"
favicon_32 = "avatar.webp"
favicon_16 = "avatar.webp"

since = 2024

enableTwemoji = true

colorScheme = "dark"
hidecolorschemetoggle = true

customCSS = ["css/carousel.css"]
customJS = ["js/carousel.js"]

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/gerblesh/"
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/gar354/"
[[params.social]]
name = "Github"
icon = "fa-brands fa-itch-io fa-2x"
weight = 2
url = "https://gerblesh.itch.io"
# Menu links
[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"
[[menu.main]]
name = "Piano"
weight = 4
url = "piano/"

[module]
[[module.imports]]
path = 'github.com/luizdepra/hugo-coder'
